# Generated by Django 2.0.5 on 2018-06-06 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaxmgr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='connection',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
