# Generated by Django 2.0.5 on 2018-06-07 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaxmgr', '0002_auto_20180606_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.CharField(default='Warszawa', max_length=50, verbose_name='Miasto'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='amount',
            field=models.IntegerField(default=0, verbose_name='Ilość'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaxmgr.Branch', verbose_name='Placówka'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vaxmgr.Vaccine', verbose_name='Szczepionka'),
        ),
    ]
